services:
  postgres:
    container_name: postgres
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER:}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD:}
    ports:
      - "5432:5432"